######################################################################
# Automatically generated by qmake (1.07a) Tue Oct 24 12:08:19 2006
######################################################################

PROGRAM = testpitch
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += pitch.h tuning.h
SOURCES += pitch.cpp testpitch.cpp tuning.cpp
